# Generated by Django 6.0.3 on 2026-03-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=255)),
                ('tipo_produto', models.CharField(max_length=255)),
                ('fornecedor', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('foto_produto', models.ImageField(upload_to='produtos/')),
            ],
            options={
                'db_table': 'tbl_produto',
            },
        ),
    ]
