# Generated by Django 6.0.3 on 2026-03-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monte_aki_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='foto_produto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='produto',
            table='tbl_produtos',
        ),
    ]
