# Generated by Django 6.0.3 on 2026-03-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monte_aki_web', '0004_alter_produto_foto_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='foto_produto',
            field=models.ImageField(upload_to='produtos/'),
        ),
    ]
